name: BMP Processor Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential expect  # Install `expect` explicitly

      - name: Build project
        run: make

      - name: Test rotations and filter
        run: |
          # Use `expect` to automate input
          expect -c '
            spawn ./main
            expect "Please, choose an input file"
            send "Airplane.bmp\r"
            expect "Enter 1-5"
            send "1\r"
          
            expect "Please, choose an input file"
            send "Airplane.bmp\r"
            expect "Enter 1-5"
            send "2\r"
          
            expect "Please, choose an input file"
            send "Airplane.bmp\r"
            expect "Enter 1-5"
            send "3\r"
          
            expect "Please, choose an input file"
            send "Airplane.bmp\r"
            expect "Enter 1-5"
            send "4\r"
          
            expect "Please, choose an input file"
            send "invalid\r"
            expect eof
          '